# Generated by Django 2.1.2 on 2018-10-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wisata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wisata', models.CharField(max_length=50)),
                ('jenis_wisata', models.CharField(choices=[('Religi', 'Religi'), ('Alam', 'Alam'), ('Tradisional', 'Tradisional'), ('Buatan', 'Buatan')], default='Alam', max_length=25)),
                ('biaya_masuk', models.CharField(max_length=50)),
                ('min_harga_makanan', models.CharField(max_length=50)),
                ('biaya_transport', models.CharField(max_length=50)),
                ('min_harga_penginapan', models.CharField(max_length=50)),
                ('jarak_dari_bandara', models.CharField(max_length=50)),
            ],
        ),
    ]
